name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install
    - name: Test
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm run ci
    - name: Deploy
      run: |
        sudo cp -r ./ /var/www/xiaoer
        cd /var/www/xiaoer
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm run stop
        npm start

