name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install
    - name: Test
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm run ci
    - name: Deploy
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /var/www/xiaoer
          git pull --rebase
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          npm i --production
          npm run stop
          npm start
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.KEY }}